sudo: false
language: node_js
node_js:
  - stable
  - "6"
  - "4"

script: npm test

env:
  global:
    - ISTANBUL_COVERAGE: yes

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
